#'////////////////////////////////////////////////////////////////////////////
#' FILE: app.R
#' AUTHOR: David Ruvolo
#' CREATED: 2020-08-03
#' MODIFIED: 2020-08-03
#' PURPOSE: primary app.R file
#' STATUS: working
#' PACKAGES: iceApp; shiny; (see description)
#' COMMENTS: This script is generated by dev/02_dev.R
#'////////////////////////////////////////////////////////////////////////////

# Launch the ShinyApp (Do not remove this comment)
# To deploy, run: rsconnect::deployApp()
# Or use the blue button on top of this file

pkgload::load_all(export_all = FALSE, helpers = FALSE, attach_testthat = FALSE)
options("golem.app.prod" = TRUE)
iceApp::run_app()
